spring:
  application:
    name: scam-awareness-platform
  profiles:
    active: dev # Default to dev for local development

server:
  port: 8080
  
# Actuator Health Check (Used by AWS Elastic Beanstalk to monitor instance health)
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
