spring:
  datasource:
    # AWS RDS PostgreSQL Configuration via Environment Variables
    # These variables will be set in the Elastic Beanstalk Environment properties
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # In production, use 'validate' and Flyway, but keeping 'update' for simplicity in demo
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  # Secret fetched from EB Environment variables to avoid hardcoding
  secret: ${JWT_SECRET}
  expiration: 86400000 # 1 day in milliseconds
